# appDefaultValues.toml

[appPaths]
rootInPN   = "Input" # Path to the input working directory, in this path.
rootOutPN  = "Output" # Path to where you want to store the training data
runCfgFN   = "runParsEx.toml"

[runIds]
expTag     = "Nalepka1"
expTestTag = "NalepkaTest1"
datasetDir = "Datasets"
projectDir = "Kostomlaty"
modelDir = "Model"
trainingResultsDir = 'TrainingResults'
predictionResultsDir = 'Prediction'
inverseResultsDir = 'InverseAnalysis'

[trainingDataset]
dataFN       = "Kostomlaty_elastic_ANN_LHS300.xlsx"
inSheet      = "OUTPUT ANN"
inColOffset  = 1
outSheet     = "INPUT ANN"
outColOffset = 1
inPars       = "#ALL#"
outPars      = "#ALL#"

[predictionDataset]
dataFN       = "Kostomlaty_elastic_ANN_LHS300.xlsx"
inSheet      = "OUTPUT ANN"
inColOffset  = 1
inPars       = "#ALL#"

[inverseAnalysisDataset]
dataFN       = "Prediction.xlsx"
inSheet      = "INPUT ANN"
inColOffset  = 1
inPars       = "#ALL#"

[training]
verbose         = 4
testSize        = 0.05
epochN          = 400
learningRate    = 10e-4
loss            = "mean_squared_error"
metrics         = "mae,mse"
validationSplit = 0.2
randomSeed      = 42
xPlotGroups     = ""
xPlotLabels     = ""

[model]
modelType = "dividedDenseModel"

[denseModel]
Layers     = "512, 1024, 512, 256, 128, 64, 16"

[dividedDenseModel]
Layers     = "1024, 512, 256, 128, 64, 16"

[dividedDenseModel.inverseParams]
inverseLearningRate = 1e-2
n_iter = 20
return_best_only = "True"
lower_limit = "[1000, 1000, 1000, 1000, 1000, 1000, -17000]"
upper_limit = "[180000, 180000, 180000, 180000, 180000, 180000, -8000]"
tolerance = 1e-7
max_iter = 200
print_freq = 100

[multiChannelModel]
Layers  = "[[['LSTM', 256], ['LSTM', 256], ['Dense', 256, 'relu'], ['Dense', 128, 'relu'], ['Dense', 64, 'relu'], ['Dense', 16, 'relu'], ['Dense', 8]], [['Dense', 8, 'relu']]]"
Inputs = "[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], [0]]"

[others]
imgExt          = 'jpg'
acknowledgement = """The “Digital twin for increased reliability and sustainability of concrete bridges” project has been financed with the state support of the Technology Agency of the Czech Republic and the Ministry of Transport of the Czech Republic within the TRANSPORT 2020+ Programme."""
